#! /bin/bash
BASEDIR="$(dirname "$0")"
TEMPFILE=downward.tmp.$$
cat > $TEMPFILE

#SEED=`date +%s`
SEED=814102613

PLANNER="$BASEDIR/downward-release"

CONFIG="$2"
shift 2

echo "$PLANNER" \
    --heuristic \""h=max()"\" \
    --search \""lazy_greedy(h, preferred=h)"\" \
    --random-seed $SEED \
    "$@" "<" output

"$PLANNER" \
    --heuristic "h=max()" \
    --search "lazy_greedy([h], preferred=[h])" \
    --random-seed $SEED \
    "$@" < $TEMPFILE
            
EXITCODE=$?
rm -f $TEMPFILE
exit $EXITCODE
